services:
  backend:
    build:
        context: .
    container_name: utrecht-bereikbaarheid-backend
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile_database
    container_name: utrecht-bereikbaarheid-database
    environment:
      - POSTGRES_USER=bereikbaarheid_user
      - POSTGRES_PASS=supersecret
      - POSTGRES_DBNAME=bereikbaarheid
      - SCHEMA_NAME=bereikbaarheid
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,pgrouting
      - ALLOW_IP_RANGE=0.0.0.0/0
      - GENERATE_ALL_LOCALE=0
    ports:
      - "25432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  generate_deps: &generate_deps
    build:
      context: .
      dockerfile: Dockerfile_python_deps
    command: --strip-extras requirements.in
    restart: no
    volumes:
        - .:/app

  upgrade_deps:
    <<: *generate_deps
    command: --strip-extras --upgrade requirements.in

networks:
  default:
    name: utrecht-bereikbaarheid

volumes:
  db_data:
