name: CI
on:
  merge_group:
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip pip-tools
          pip-sync requirements.txt

      - name: Lint
        run: flake8

      - name: Check formatting
        run: black . --check --diff

      - name: Run tests
        run: pytest --cov-report term-missing --cov=src.app tests
