name: CI
on:
  merge_group:
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Prepare Python env
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - name: Install dependencies
        run: |
          pip install --upgrade pip pip-tools
          pip-sync requirements/base.txt requirements/production.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Lint
        run: flake8

      - name: Check formatting
        run: black . --check --diff

      - name: Run tests
        run: pytest --cov-report term-missing --cov=src.app tests
